a = input('Digite algo:')
print('O tipo primitivo desse valor é:', type(a))
print('Só tem espaço?', a.isspace())
print('É um número?', a.isnumeric())
print('É alphabetic?', a.isalpha())
print('É alphanumerics', a.isalnum())
print('Está em maisculo?', a.isupper())
print('Está em minusulo:', a.islower())
print('Está Capitalizada?', a.istitle())